# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FastCart' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod "BarcodeScanner"
    pod 'AFNetworking'
    pod 'BraintreeDropIn'
    pod 'Braintree/Apple-Pay'
    pod 'Braintree/PayPal'
    pod 'Braintree/Venmo'
    pod 'Braintree/3D-Secure'    
    pod 'FBSDKCoreKit'
    pod 'FBSDKShareKit'
    pod 'FBSDKLoginKit'
    # Modified to handle URLs.
    pod 'EVReflection', :git => "https://github.com/Omnistyle/EVReflection.git"
    pod 'Parse'
    pod "MXParallaxHeader"
    # We've made modification to the code for our own uses.
    pod "SAParallaxViewControllerSwift", :git => "https://github.com/Omnistyle/SAParallaxViewControllerSwift.git"
    pod 'SCLAlertView'
    pod 'TLYShyNavBar'
    pod 'SideMenu'
    pod 'LUExpandableTableView'
    pod 'ASHorizontalScrollView'
    # data
    pod 'Mixpanel'
end
